export default {
    ADD_ITEM: 'ADD_ITEM',
    TOGGLE_COMPLETE_TODO: 'TOGGLE_COMPLETE_TODO',
    SET_FILTER: 'SET_FILTER',
    CLEAR_COMPLETED: 'CLEAR_COMPLETED',
    SHOW_MODAL: 'SHOW_MODAL',
    HIDE_MODAL: 'HIDE_MODAL',
    EDIT_TODO_TEXT: 'EDIT_TODO_TEXT'
};
